# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LibertyinDeath
email: libertyindeath@mail.com
username: Dave Alex
github: https://github.com/LibertyinDeath
description: > # this means to ignore newlines until "baseurl:"
  Your value doesn't decrease based on someone's inability to see your worth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
safe: false
# Build settings
markdown: kramdown
kramdown:
       input: GFM
       hard_wrap: true
